server:
    #服务端口
    port: 80
    servlet:
        context-path: /
    context:
        url: http://xejf.mdit.edu.cn/

logging:
    level:
        org.springframework: error
    config: classpath:log4j2.xml

spring:
    datasource:
        dynamic:
            primary: master #设置默认的数据源或者数据源组,默认值即为master
            strict: true #设置严格模式,默认false不启动. 启动后在未匹配到指定数据源时候回抛出异常,不启动会使用默认数据源.
            datasource:
                master:
                    url: jdbc:sqlserver://192.168.19.11:1433;DatabaseName=Q1_Base
                    username: sa
                    password: Yczn1.234
                    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
                storage:
                    url: jdbc:sqlserver://192.168.19.11:1433;DatabaseName=Q1_Storage
                    username: sa
                    password: Yczn1.234
                    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    redis:
        ###Redis数据库索引（默认为0）
        database: 0
        host: 192.168.19.13
        port: 6379
        jedis:
            pool:
                ###连接池最大连接数（使用负值表示没有限制）
                max-active: 8
                ###连接池最大阻塞等待时间（使用负值表示没有限制）
                max-wait: -1
                ###连接池中的最大空闲连接
                max-idle: 5
                ###连接池中的最小空闲连接
                min-idle: 0
        ###连接超时时间（毫秒）
        timeout: 10000
        password: Yczn1.234
    data:
        redis:
            repositories:
                enabled: false

    rabbitmq:
        host: 192.168.19.12
        port: 5672
        username: admin
        password: Yczn1.234
        virtual-host: /
        publisher-confirms: true
        listener:
            simple:
                auto-startup: true
                concurrency: 10
                default-requeue-rejected: true
                max-concurrency: 10
                prefetch: 1

mybatis-plus:
    # 如果是放在src/main/java目录下 classpath:/com/*/*/mapper/*Mapper.xml
    # 如果是放在resource目录 classpath:/mapper/**.xml
    mapper-locations: classpath:/mapper/*/**.xml

#支付回调地址
wexinpay:
    notify:
        url: http://xejf.mdit.edu.cn/weixin/notifyPay

consume:
    isCardbagsConsume: true #是否使用钱包消费